# Generated by Django 4.2.4 on 2025-07-28 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BareActsAgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.0-flash', max_length=50)),
                ('Router_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.0-flash', max_length=50)),
                ('Retriever_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.0-flash', max_length=50)),
                ('Grader_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.5-flash', max_length=50)),
                ('Answer_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.5-pro', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extension_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Querry', models.TextField()),
                ('Web_Search_Answer', models.TextField()),
                ('IT_Act_Answer', models.TextField()),
                ('IT_Act_Document', models.TextField()),
                ('BNS_Act_Answer', models.TextField()),
                ('BNS_Act_Document', models.TextField()),
                ('BSA_Act_Answer', models.TextField()),
                ('BSA_Act_Document', models.TextField()),
                ('Acts_Combined_Answers', models.TextField()),
                ('Web_Bare_Act_Combined', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Act_name', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='ReflexionAgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reflexion_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.5-pro', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VectorDBInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Checked_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('DB_name', models.CharField(max_length=100)),
                ('Status', models.BooleanField(default=False)),
                ('Records_count', models.IntegerField(default=0)),
                ('Path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WebsearchAgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Querry_Generator_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('llama2:chat', 'OLLAMA>llama2:chat')], default='gemini-2.0-flash', max_length=50)),
                ('Reflexion_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('llama2:chat', 'OLLAMA>llama2:chat')], default='gemini-2.5-flash', max_length=50)),
                ('Answer_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('llama2:chat', 'OLLAMA>llama2:chat')], default='gemini-2.5-pro', max_length=50)),
                ('Initial_Querry', models.SmallIntegerField(default=3)),
                ('Max_Research_Loops', models.SmallIntegerField(default=2)),
            ],
        ),
    ]
