# Generated by Django 4.2.4 on 2025-07-31 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension_Data_BNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Querry', models.TextField()),
                ('BNS_Act_Answer', models.TextField()),
                ('BNS_Act_Document', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Extension_Data_BSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Querry', models.TextField()),
                ('BSA_Act_Answer', models.TextField()),
                ('BSA_Act_Document', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Extension_Data_IT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Querry', models.TextField()),
                ('IT_Act_Answer', models.TextField()),
                ('IT_Act_Document', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
