# Generated by Django 4.2.4 on 2025-07-31 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_extension_data_bns_extension_data_bsa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension_Data_Web_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Querry', models.TextField()),
                ('Web_Answer', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
