# Generated by Django 4.2.4 on 2025-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_extension_data_web_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension_data_web_search',
            name='Search_Querry',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extension_data_web_search',
            name='Sources_Gathered',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
