# Generated by Django 4.2.4 on 2025-08-03 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_extension_data_web_search_search_querry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langgraph_Deployed_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_Path', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
