# Generated by Django 4.2.4 on 2025-08-06 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_langgraph_deployed_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langgraph_Deployed_Agent_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Web_Search_Agent', models.TextField()),
                ('BSA_Agent', models.TextField()),
                ('BNS_Agent', models.TextField()),
                ('Chat', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('API_Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.langgraph_deployed_api')),
            ],
        ),
    ]
