# Generated by Django 4.2.4 on 2025-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_langgraph_deployed_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='langgraph_deployed_agent_name',
            name='IT_Agent',
            field=models.TextField(default=''),
        ),
    ]
