# Generated by Django 4.2.4 on 2025-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_langgraph_deployed_agent_name_it_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension_data',
            name='Thread_Id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='extension_data_bns',
            name='Thread_Id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='extension_data_bsa',
            name='Thread_Id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='extension_data_it',
            name='Thread_Id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='extension_data_web_search',
            name='Thread_Id',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
