# Generated by Django 4.2.4 on 2025-09-24 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_extension_data_thread_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension_Data_DPDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thread_Id', models.TextField(blank=True, default='', null=True)),
                ('User_Querry', models.TextField()),
                ('BNS_Act_Answer', models.TextField()),
                ('BNS_Act_Document', models.TextField()),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Answer_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.5-pro', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Grader_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.5-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Model_Name',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Retriever_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Router_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='reflexionagentconfiguration',
            name='Reflexion_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest')], default='gemini-2.5-pro', max_length=50),
        ),
        migrations.AlterField(
            model_name='websearchagentconfiguration',
            name='Answer_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash')], default='gemini-2.5-pro', max_length=50),
        ),
        migrations.AlterField(
            model_name='websearchagentconfiguration',
            name='Querry_Generator_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='websearchagentconfiguration',
            name='Reflexion_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash')], default='gemini-2.5-flash', max_length=50),
        ),
    ]
