# Generated by Django 4.2.4 on 2025-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_extension_data_dpdp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='langgraph_deployed_agent_name',
            name='DPDP_Agent',
            field=models.TextField(default='agent_DPDP'),
        ),
        migrations.AlterField(
            model_name='langgraph_deployed_agent_name',
            name='BNS_Agent',
            field=models.TextField(default='agent_BNS'),
        ),
        migrations.AlterField(
            model_name='langgraph_deployed_agent_name',
            name='BSA_Agent',
            field=models.TextField(default='agent_BSA'),
        ),
        migrations.AlterField(
            model_name='langgraph_deployed_agent_name',
            name='Chat',
            field=models.TextField(default='agent_all'),
        ),
        migrations.AlterField(
            model_name='langgraph_deployed_agent_name',
            name='IT_Agent',
            field=models.TextField(default='agent_IT'),
        ),
        migrations.AlterField(
            model_name='langgraph_deployed_agent_name',
            name='Web_Search_Agent',
            field=models.TextField(default='agent_WS'),
        ),
    ]
