# Generated by Django 4.2.4 on 2025-09-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_langgraph_deployed_agent_name_dpdp_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extension_data_dpdp',
            old_name='BNS_Act_Answer',
            new_name='DPDP_Act_Answer',
        ),
        migrations.RenameField(
            model_name='extension_data_dpdp',
            old_name='BNS_Act_Document',
            new_name='DPDP_Act_Document',
        ),
    ]
