# Generated by Django 4.2.4 on 2025-09-30 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_githhub_model_api_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual_explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thread_Id', models.TextField(blank=True, default='', null=True)),
                ('doc', models.FileField(upload_to='media/')),
                ('agent_name', models.TextField(default='agent_DPDP')),
                ('Updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='githhub_model_api',
            name='API_Path_Azure',
        ),
        migrations.AddField(
            model_name='extension_data',
            name='DPDP_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='extension_data',
            name='DPDP_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Answer_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('meta/Llama-4-Scout-17B-16E-Instruct(github)', 'GithubModels>Openai-GPT-5')], default='gemini-2.5-pro', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Grader_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('meta/Llama-4-Scout-17B-16E-Instruct(github)', 'GithubModels>Openai-GPT-5')], default='gemini-2.5-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Model_Name',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('meta/Llama-4-Scout-17B-16E-Instruct(github)', 'GithubModels>Openai-GPT-5')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Retriever_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('meta/Llama-4-Scout-17B-16E-Instruct(github)', 'GithubModels>Openai-GPT-5')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='bareactsagentconfiguration',
            name='Router_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('meta/Llama-4-Scout-17B-16E-Instruct(github)', 'GithubModels>Openai-GPT-5')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='Acts_Combined_Answers',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='BNS_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='BNS_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='BSA_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='BSA_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='IT_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='IT_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='User_Querry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='Web_Bare_Act_Combined',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data',
            name='Web_Search_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_bns',
            name='BNS_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_bns',
            name='BNS_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_bns',
            name='User_Querry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_bsa',
            name='BSA_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_bsa',
            name='BSA_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_bsa',
            name='User_Querry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_dpdp',
            name='DPDP_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_dpdp',
            name='DPDP_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_dpdp',
            name='User_Querry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_it',
            name='IT_Act_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_it',
            name='IT_Act_Document',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_it',
            name='User_Querry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_web_search',
            name='Search_Querry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_web_search',
            name='Sources_Gathered',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_web_search',
            name='User_Querry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extension_data_web_search',
            name='Web_Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reflexionagentconfiguration',
            name='Reflexion_Model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('meta/Llama-4-Scout-17B-16E-Instruct(github)', 'GithubModels>Openai-GPT-5')], default='gemini-2.5-pro', max_length=50),
        ),
    ]
