# Generated by Django 4.2.4 on 2026-02-26 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflexionAgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reflexion_Model', models.CharField(choices=[('gemini-2.0-flash', 'GOOGLE>gemini-2.0-flash'), ('gemini-2.5-flash', 'GOOGLE>gemini-2.5-flash'), ('gemini-2.5-pro', 'GOOGLE>gemini-2.5-pro'), ('gemini-1.5-flash', 'GOOGLE>gemini-1.5-flash'), ('gemma3:4b', 'OLLAMA>gemma3:4b'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('llama3.2:1b', 'OLLAMA>llama3.2:1b'), ('deepseek-r1:latest', 'OLLAMA>deepseek-r1:latest'), ('gemma2:2b', 'OLLAMA>gemma2:2b'), ('deepseek-r1:1.5b', 'OLLAMA>deepseek-r1:1.5b'), ('llama2:chat', 'OLLAMA>llama2:chat'), ('llama3.2:latest', 'OLLAMA>llama3.2:latest'), ('meta/Llama-4-Scout-17B-16E-Instruct(github)', 'GithubModels>Openai-GPT-5')], default='gemini-2.5-pro', max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='bareactfilemodel',
            old_name='updated_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='githhubmodelapi',
            old_name='Updated_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='langgraph_deployed_agent_name',
            old_name='Updated_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='langgraphdeployedapi',
            old_name='Updated_on',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='bareactsagentconfiguration',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vectordbinformation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='websearchagentconfiguration',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
